name: qiita_searcher
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  flutter_riverpod:
  freezed_annotation:
  go_router:
  http:
  intl:
  riverpod_annotation:
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner:
  custom_lint:
  freezed:
  go_router_builder:
  json_serializable:
  riverpod_generator:
  riverpod_lint:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true